export const RESERVATION_REPOSITORY = 'ReservationRepository'
export const RESERVATIONS_MICROSERVICE = 'RESERVATIONS_MICROSERVICE'
export const RESERVATIONS_QUEUE = 'reservations_queue'

export const ESTABLISMENT_MICROSERVICE_URL = 'ESTABLISMENT_MICROSERVICE_URL'